CREATE TABLE CrmRoles (
    Id UNIQUEIDENTIFIER CONSTRAINT PK_CrmRoles PRIMARY KEY DEFAULT (NEWID()),
    CreatedDate DATETIME2(0) NOT NULL DEFAULT (GETUTCDATE()),
    UpdatedDate DATETIME2(0),
    Name NVARCHAR(100) NOT NULL,
)

CREATE UNIQUE INDEX UIX_CrmRoles ON CrmRoles (Name)
